version: '3.5'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=AWTAP0NOm0v6KNACjIf5E7UK
      - POSTGRES_DB=basket_db
    ports:
      - '5433:5433'
    expose:
      - '5433'

  rabbitmq:
      image: rabbitmq:latest
      container_name: rabbitmq
      ports:
        - "5673:5673"
        - "15673:15673"
